### PR TITLE
Refactoring of the tools

### PR DESCRIPTION
**Pull request by guyzmo**
Hi,

you might not want to include my fork's work in your original tree, as I made quite a bunch of changes, it is now:
- setuptools based
- using one script entry point `pea` (for `python eagle automation`, I hope you don't mind the rename)
- added docopt based argument parsing, and a `git` like scheme
  - you run `pea diff` for the old `eaglediff`, `pea export` for the old `eagleexport`…
- added BOM handling in `export`, by doing `pea export foo.sch bom out1.json out2.csv out3.xlsx` (you can specify multiple files and get multiple formats output)

Oh, and I made it python3 ready as well! 

I've also uploaded it to pypi, because I want my colleagues and friends to start using it, I hope you won't mind (I always consider it's better to apology than ask for permission):

https://pypi.python.org/pypi/eagle_automation

What I envision next for the script is:
1. get rid of the python based configuration file, it's poor security and prone to bugs. It's better to use either `yaml`, `json` or `ini` format. Though what needs to be addressed is to have a proper handling of configuration through argument, project, user and global.
2. make as much as possible using pyeagle and parsing of the new eagle format, instead of going through eagle directly. It's more elegant, and I guess more powerful.

Anyway, thank you a lot for your original work :+1: 

I'm barely doing the bells and whistles to make it actually nicer to use :-)

### CODE REVIEW

**Comment by guyzmo** [comment]
* added yaml configuration scheme replacing python based one!
* added also configuration setup using the tool, e.g.:

    pea -c myproject_eagle_automation.conf -c eagle=/usr/local/bin/eagle export project.sch bom project.csv

will look for "default" configuration files in `/etc/eagle_automation.conf`, `~/.eagle_automation.conf`, `~/.config/eagle_automation.conf`, `./eagle_automation.conf` and then will evaluate command line `-c` in order so that you can setup values and load other configuration files. Which is pretty convenient for having a global configuration that sets up dpi and eagle path, and local configuration which will setup layers…

Though, thinking about it, I haven't been very fussy doing it. I believe that a configuration key such as LAYER will get overwritten by a new setting instead of just updating it. Might need a fix to check if we're about to update a key with a dict and the key already has a dict, then update the key (and recurse for that dict's values).

**Comment by guyzmo** [comment]
ok, last bunch of commits:

added support for saving file, and generation of a multiple page PDF for sch with multiple sheets.

sadly I had to drop the feature that opens a file "per default". I might add `xdg-open`/`open` support with a command line option to bring it back.

Though, besides nice to have improvements (like switching to pyeagle and do the work over the XML for most of the work, instead of using eagle all the time… I'm sure we could make a visual diff based on the eagle XML file contents :-) ) I think I've added all the features I needed for my everyday use :-)

Obviously, the lack of unit testing means we'll need to debug it "in the wild", given the amount of changes I've done in a little time.

HTH

**Comment by guyzmo** [comment]
Ok, found a few bugs today, so I thought I'd also fix the configuration file scheme as well :-)

**Comment by avian2** [comment]
This sounds awesome. I'm happy you took the time to update it (and to let me know). I'm still using an old Eagle license and can't work on files in the new format. Also, first time I've heard of pyeagle.

 I don't mind you put it on pypi. I'll have closer look and give you some feedback as soon as I find time.

**Comment by guyzmo** [comment]
ok, now that you say that, it might be a good idea to fallback to single page when the file is not parsable in XML. BTW, if you wonder why I made that many version bumps, it's because I have to bump version number each time I'm uploading to pypi. :-)

**Comment by guyzmo** [comment]
Hi,

I added a bunch of new stuff:

- made the code mostly pep8 compliant (and that includes switching from tabs to spaces)
- used context managers for temporary directories
- fixed a few bugs (like exceptions were badly declared and used)
- refactored utility functions out into a standalone module, same for exceptions
- replaced "manual" filling of a dict (for export commands) with a class decorator
- added a test file skeleton
- added a parts database management scheme for handling alternatives (not variants!) of components
- refactored bom generation to have a single API for outputting in parallel in any format
- added pyeagle based bom generation
  - the target py_bom is using that scheme, old_bom is the original, bom is trying py_bom, but if it fails it tries old_bom

Obviously, I haven't much worked on documentation aspects, and I need to add testing to ensure code stability, as the code base is growing quite a lot ;-)

**Comment by guyzmo** [comment]
Given all the changes I made, it looks more and more like a new project, even though I make my best to keep all the original features working as is ;-) So I can understand if you aren't taking the PR ;-)

**Comment by avian2** [comment]
Thanks for sharing your work. I appreciate that you've documented the changes you've made here. 

I agree that this looks more like a new project than an incremental update to existing tools. Because of that, I'm closing this pull request. I will keep the old tools in my repository, since I have too many existing projects that I do not want to migrate to the new command line interface and config syntax you use.

I added a link to your repository to the README file here, so that other people can more easily find your updated version.

**Pull request closed without merging**
